baseURL: "https://examplesite.com/"
title: Aji Arya
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-182251419-3

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Aji Arya
    description: "Aji Arya's Personal Blog"
    keywords: [Blog, Portfolio, PaperMod]
    author: Aji Arya
    # author: ["Me", "You"] # multiple authors
    # images: [""]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Aji Arya"
        # icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: no # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Config, Deploy, & Chill! \U0001F60E"
        Content: Welcome to my blog

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/ajiarya"
        - name: instagram
          url: "https://instagram.com/ajiaryaa"
        - name: twitter
          url: "https://twitter.com/aryasaurus"
        - name: github
          url: "https://github.com/ajiarya"

    analytics:
        google:
            SiteVerificationTag: "7xkl7tm1-iJxieMKGetoXQpqJffAVKatOFgXg7ddX_Y"
        #bing:
        #    SiteVerificationTag: "XYZabc"
        #yandex:
        #    SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/ajiarya/blog/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: imtek
          name: imtek.id
          url: https://imtek.id
          weight: 30
